### ISSUE TITLE
A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true.

### ISSUE THREAD

**Issue by alexmuro** [joostfarla/serverless-cors-plugin#1]
When using the cors plugin I always get the following error 
Response to preflight request doesn't pass access control check: A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true.
I'm using a very basic s-function config:
```
{
  "functions": {
    "eio": {
      "custom": {
        "excludePatterns": [],
        "envVars": [],
        "cors": {
          "allow": {
            "origin": "*"
          }
        }
      },
      "handler": "modules/falcor/eio/handler.handler",
      "timeout": 6,
      "memorySize": 1024,
      "eventSourceArn": "",
      "endpoints": [
        {
          "path": "falcor/eio",
          "method": "GET",
          "authorizationType": "none",
          "apiKeyRequired": false,
          "requestParameters": {},
          "requestTemplates": {
            "application/json": ""
          },
          "responses": {
            "400": {
              "statusCode": "400"
            },
            "default": {
              "statusCode": "200",
              "responseParameters": {},
              "responseModels": {},
              "responseTemplates": {
                "application/json": ""
              }
            }
          }
        }
      ]
    }
  }
}
```

 and I have added the plugin to the s-project.json. Its clearly doing something because the OPTION method gets created in the API gateway which wouldn't happen witth adding the cors plugin.

**Comment by joostfarla** [comment]
Thank again for reporting! You are getting this error in the browser console, right?

I suspect you have set the [`withCredentials`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) option to `true` in whatever JS library that is performing the XHR request? If yes, did you mean to make authorized requests?

If you really want to make authorized requests:
* The `Access-Control-Allow-Credentials` header has to be set tor `true`. However, the plugin does not support this header at this time. I'll probably release support for this today or tomorrow.
* You have to set a specific host in the `Access-Control-Allow-Origin` header. CORS doen not allow a wildcard (*) origin for authorized requests.

**Comment by alexmuro** [comment]
That was it, thank you!
Also thank you for this plugin its a huge time saver.
I am using https://github.com/Netflix/falcor-http-datasource to make requests and it has some odd defaults.

**Comment by chadkouse** [comment]
What do you think about an option to allow you to pass back the host that is making the request in the `Access-Control-Allow-Origin` header -- in other words, instead of `*` it just looks at who's calling and returns that host name -- this would allow authenticated requests to come from anywhere.

**Comment by joostfarla** [comment]
@chadkouse Thanks for reaching out! That is indeed something I've been thinking about and it definitely could be an interesting addition for authorized requests! I'll create an issue for this.
