### ISSUE TITLE
OPTIONS mock type

### ISSUE THREAD

**Issue by Alua-Kinzhebayeva** [joostfarla/serverless-cors-plugin#14]
Is there any reason for not having OPTIONS created with Mock endpoint? Is it on the RoadMap or there is technical issue with that?
Really sorry about asking it, I remember some discussions in gitter, but totally forgot the outcome of them.

**Comment by Alua-Kinzhebayeva** [comment]
I see ```type:           'MOCK'``` in the source code. That is strange then that all our OPTIONS have lambda integrated.

**Comment by joostfarla** [comment]
@Alua-Kinzhebayeva Thanks for reporting!

This actually was broken since the Serverless v0.4 update. Just implemented a workaround and released v0.3.1!

**Comment by Alua-Kinzhebayeva** [comment]
@joostfarla that is totally awesome! thanks for the release! It is such a huge relief.
