### ISSUE TITLE
v2.1 exported CORS correctly, v3.1 no longer works

### ISSUE THREAD

**Issue by brainframe-me** [joostfarla/serverless-cors-plugin#15]
Hi,

Is there something significant that changed? I was using serverless v0.4.2 together with serverless-cors-plugin v0.2.1 and then a "serverless endpoint deploy --all" worked perfectly to include the preflight checks etc.. when run in the root of the project.
Now when using v0.4.2 with v0.3.1, the same command suddenly crashes with following error:

C:\DATA\serverless-4kgaw\nodejscomponent\resource\show>serverless endpoint deploy --all
C:\Users\myusername\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\main\async.js:43
        fn = function () { throw arg; };
                           ^

ServerlessError: Missing required config.component, config.module, config.function, config.endpointMethod, config.endpointPath
    at new ServerlessError (C:\Users\myusername\AppData\Roaming\npm\node_modules\serverless\lib\ServerlessError.js:17:11)
    at new ServerlessEndpoint (C:\Users\myusername\AppData\Roaming\npm\node_modules\serverless\lib\ServerlessEndpoint.js:24:122)
    at C:\DATA\serverless-4kgaw\node_modules\serverless-cors-plugin\src\index.js:98:29
    at arrayEach (C:\DATA\serverless-4kgaw\node_modules\serverless-cors-plugin\node_modules\lodash\lodash.js:482:11)
    at Function.forEach (C:\DATA\serverless-4kgaw\node_modules\serverless-cors-plugin\node_modules\lodash\lodash.js:7720:11)
    at ServerlessCors.addPreflightRequests (C:\DATA\serverless-4kgaw\node_modules\serverless-cors-plugin\src\index.js:78:9)
From previous event:
    at C:\Users\myusername\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:157:29
    at Array.reduce (native)
    at C:\Users\myusername\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:156:30
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Serverless._execute (C:\Users\myusername\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:154:10)
    at Serverless.actions.(anonymous function) (C:\Users\myusername\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:382:20)
    at Serverless.command (C:\Users\myusername\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:351:38)
    at Object.<anonymous> (C:\Users\myusername\AppData\Roaming\npm\node_modules\serverless\bin\serverless:16:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

I've got following code in s-module.json:
{
  "name": "auth",
  "profile": "aws-v0.3.1",
  "custom": {
    "cors": {
      "allowOrigin": "*",
      "allowHeaders": [
        "Content-Type",
        "X-Amz-Date",
        "Authorization",
        "X-Api-Key",
        "x-amz-security-token",
        "Access-Control-Allow-Origin"
      ]
    }
  },
  "cloudFormation": {
    "resources": {},
    "lambdaIamPolicyDocumentStatements": []
  }
}

Any ideas?

**Comment by joostfarla** [comment]
In Serverless v0.4 the module concept was dropped, but it has been kept backwards compatible. This change has been reflected in the plugin in v0.3, but without backwards compatibility.

So, probably the best way to solve this is by getting rid of your `s-module.json` files. Furthermore, the plugin now supports component-level policies. Does this help you?

**Comment by brainframe-me** [comment]
Great, that was the problem.
Thanks!

Cox Davy
+352 621437914
www.brainframe.lu
*Brainframe Technologies S.àr.l. au capital de 20.000 € *
*Autorisation d'établissement: N° 10064632 | RCSL B.203.013 | TVA:
LU28203280 *

*Disclaimer*

*Les informations contenues dans ce message sont destinées exclusivement à
l’usage de la personne à laquelle elles sont adressées. Elles peuvent
contenir des données confidentielles et/ou privilégiées et/ou protégées par
des droits de propriété intellectuelle ou d’autres lois. Si vous avez reçu
ce message par erreur, veuillez le détruire, ainsi que toutes ses annexes,
et notifier son expéditeur ; il vous est interdit de copier ou d’utiliser
ce messages ou ses annexes ou de divulguer son contenu à quiconque. La
transmission de données par e-mail ne peut être garantie comme un moyen sûr
et infaillible, ni comme étant exempt de tout virus. L’expéditeur décline
toute responsabilité en cas de perte ou de dommage résultant de ce message
ou de son utilisation, quelle qu’elle soit. *

*The information contained in this message is intended for the addressee
only and may contain confidential and/or privileged information and/or
information protected by intellectual property rights or other legal rules.
If you are not the intended recipient, please delete this message and any
attachment to it and notify the sender; you may not copy or use this
message or its attachments in any way nor disclose its contents to anyone.
Emails cannot be guaranteed to be secure or to be error or virus free. No
liability is accepted by the sender for any loss damage arising in any way
from this message or its use. *

On Tue, Feb 16, 2016 at 4:42 PM, Joost Farla <notifications@github.com>
wrote:

> In Serverless v0.4 the module concept was dropped, but it has been kept
> backwards compatible. This change has been reflected in the plugin in v0.3,
> but without backwards compatibility.
>
> So, probably the best way to solve this is by getting rid of your
> s-module.json files. Furthermore, the plugin now supports component-level
> policies. Does this help you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joostfarla/serverless-cors-plugin/issues/15#issuecomment-184737231>
> .
>

-- 
*Disclaimer*

*The information contained in this message is intended for the addressee 
only and may contain confidential and/or privileged information and/or 
information protected by intellectual property rights or other legal rules. 
If you are not the intended recipient, please delete this message and any 
attachment to it and notify the sender; you may not copy or use this 
message or its attachments in any way nor disclose its contents to anyone. 
Emails cannot be guaranteed to be secure or to be error or virus free. No 
liability is accepted by the sender for any loss damage arising in any way 
from this message or its use. *

*Les informations contenues dans ce message sont destinées exclusivement à 
l’usage de la personne à laquelle elles sont adressées. Elles peuvent 
contenir des données confidentielles et/ou privilégiées et/ou protégées par 
des droits de propriété intellectuelle ou d’autres lois. Si vous avez reçu 
ce message par erreur, veuillez le détruire, ainsi que toutes ses annexes, 
et notifier son expéditeur ; il vous est interdit de copier ou d’utiliser 
ce messages ou ses annexes ou de divulguer son contenu à quiconque. La 
transmission de données par e-mail ne peut être garantie comme un moyen sûr 
et infaillible, ni comme étant exempt de tout virus. L’expéditeur décline 
toute responsabilité en cas de perte ou de dommage résultant de ce message 
ou de son utilisation, quelle qu’elle soit. *

**Comment by joostfarla** [comment]
> Great, that was the problem.
> Thanks!
