### ISSUE TITLE
Pass caller identity from API GW to execute lambda

### ISSUE THREAD

**Issue by brainframe-me** [joostfarla/serverless-cors-plugin#16]
I'm using temporary credentials from cognito to call API gateway:
            var apigClient = apigClientFactory.newClient(
                    {
                        accessKey: AWS.config.credentials.accessKeyId,
                        secretKey: AWS.config.credentials.secretAccessKey,
                        sessionToken: AWS.config.credentials.sessionToken,
                        region: AWS.config.region
                    }
            );

Is it possible to forward these credentials from API GW to Lambda?

I see the option "Invoke with caller credentials" in the console, but after using serverless-cors-plugin to update my API, this option is always disabled. So I guess there is a parameter for this?

When I manually check "Invoke with caller credentials" in the console after all CORS were correct, I think the function messes up the CORS settings because then I get "No 'Access-Control-Allow-Origin' header is present on the requested resource.". 

I tried with "allowCredentials": true, but does not seem to work.

**Comment by joostfarla** [comment]
@brainframe-me the plugin should only modify the following:
* It adds some CORS response headers to each endpoint response, but it preserves existing headers.
* It adds OPTIONS endpoints for preflighted requests. These are MOCK endpoint so they should not call a Lambda.

I'm not sure if your issue is related to the plugin, since it does not touch one of the above. It could however be related to https://github.com/joostfarla/serverless-cors-plugin/issues/2.

Are you still experiencing this issue?

**Comment by brainframe-me** [comment]
No thanks

**Comment by jalleyne** [comment]
@brainframe-me where you ever able to get this property set in serverless?

**Comment by brainframe-me** [comment]
I didn and if I remember well it was part of the s-function.json. But I'm not sure, and it is a bit to far away at the moment. This is how the relevant part of my s-funciton looked:

### beginning of the file omitted ####
"endpoints": [
    {
      "path": "auth/{operation}",
      "method": "POST",
      "type": "AWS",
      "authorizationType": "none",
      "apiKeyRequired": false,
      "requestParameters": {},
      "requestTemplates": {
        "application/json": {
          "operation": "$input.params('operation')",
          "authorization": "$input.params().header.get('Authorization')",
          "payload": "$input.json('$')",
          "identity": "$context.authorizer.princialId"
        }
      },
      "responses": {
        "Bad Request.*": {
          "statusCode": "400"
        },
        "Unauthorized.*": {
          "statusCode": "401"
        },
        "Not Found.*": {
          "statusCode": "404"
        },
        "Conflict.*": {
          "statusCode": "409"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {},
          "responseModels": {
            "application/json": "Empty"
          },
          "responseTemplates": {
            "application/json": ""
          }
        }
      }
    },
    {
      "path": "auth/{operation}",
      "method": "OPTIONS",
      "type": "MOCK",
      "requestTemplates": {
        "application/json": "{\"statusCode\": 200}"
      },
      "responses": {
        "default": {
          "statusCode": "200",
          "responseParameters": {
            "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,Cache-Control'",
            "method.response.header.Access-Control-Allow-Methods": "'*'",
            "method.response.header.Access-Control-Allow-Origin": "'*'"
          },
          "responseModels": {},
          "responseTemplates": {
            "application/json": ""
          }
        }
      }
    }
  ],
### rest of the file omitted ####

And I think it is passed somewhere with "authorization": "$input.params().header.get('Authorization')", OR "identity": "$context.authorizer.princialId", but I'm not sure anymore.


Your handler can then look a bit like this;

function createJWT(userId, expiresIn) {
    var exp;
    if (config.EXPIRES_IN) {
        exp = moment().add(config.EXPIRES_IN, 'seconds');
    }
    else if (expiresIn) {
        exp = moment().add(expiresIn, 'seconds');
    }
    else {
        exp = moment().add(14, 'days');
    }
    console.log('createJWT exp', exp.format());

    var payload = {
        sub: userId,
        iat: moment().unix(),
        exp: exp.unix(),
    };
    console.log('createJWT payload', payload);

    return jwt.encode(payload, config.TOKEN_SECRET);
}

module.exports.handler = function (event, context) {
    var tokenCallback = function (err, data) {
        if (err) {
            context.fail(makeError(err));
        }
        else {
            context.succeed({token: createJWT(data.id)});
        }
    };
    function checkAuthenticated(callback) {
        var authorization = event.authorization;
        delete event.authorization;

        var t = checkJWT(authorization);
        if (t.message) {
            callback('SecurityGroup:Public');
        }
        else {
            callback(t);
        }
    }  
  var ensureAuthenticated = function (callback) {
        var authorization = event.authorization;
        delete event.authorization;

        var t = checkJWT(authorization);
        if (t.message) {
            context.fail(new Error('Unauthorized: ' + t.message));
        }
        else {
            callback(t);
        }
    };
	
   ## Main program:
	checkAuthenticated(function (userId) {
	 #do something with either public or userId
	}
	
	#Or

	ensureAuthenticated(function (userId) {
	 #only continues if you were authenticated
	}
}


Definitely not the best code, but I finally got it working.
Hope it works for you. If not I won't be able to help any further, sorry...
