### ISSUE TITLE
Still need to use the "Enable CORS" feature on AWS Console to get CORS to work

### ISSUE THREAD

**Issue by aexmachina** [joostfarla/serverless-cors-plugin#28]
I've just installed this plugin on a Serverless 0.5.6 project and it does create the OPTIONS endpoints, but my HTTP requests are failing with the following error message:

```
Fetch API cannot load .... Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
However, if I go in to the AWS Console and use the "Enable CORS" feature then it all works as expected.

I also noticed that `endpoint remove` doesn't remove the OPTIONS endpoints.

**Comment by joostfarla** [comment]
Hello @aexmachina! Can you share your CORS configuration? Which commands did you run to perform the deployment?

The `remove` function indeed does not remove the preflight (`OPTIONS`) endpoints. Unfortunately, there's not much we can do about that in the current (stable) version of Serverless. V1.0 however has native support for CORS!

**Comment by aexmachina** [comment]
Hi @joostfarla, not sure what you're asking for but here's the `custom` from the `s-function.json` block:

```
  "custom": {
    "cors": {
      "allowOrigin": "*",
      "allowHeaders": ["Content-Type", "X-Amz-Date", "Authorization", "X-Api-Key"]
    }
  }
```

**Comment by joostfarla** [comment]
Hi @aexmachina, your configuration looks fine! Some things you could check:
* Is the plugin enabled in your `s-project.json` file?
* Did you deploy the endpoints using `serverless deploy -a` (the `-a` flag is important)
* Are you using any custom models or other plugins?

**Comment by aexmachina** [comment]
Yes, yes, and just the Babel plugin.

**Comment by joostfarla** [comment]
Hmm strange, can you check what the exact response (status code + headers) of the `OPTIONS` endpoint is?

You can check this via your browser's developer tools or using the Postman client.

**Comment by aexmachina** [comment]
@joostfarla it turns out it was a problem with the API Key and API Gateway providing unhelpful error messages.
